export const CONTACT_INFO = {
  COMPANY_NAME: 'Sunny Solar',
  PHONE: '1300 030 479',
  PHONE_RAW: '1300030479',
  PHONE_DISPLAY: '1300 030 479',
  EMAIL: 'info@sunnysolar.com.au',
  ADDRESS: '10A Burralong Dr, Wondunna QLD 4655, Australia',
  ADDRESS_LINE_1: '10A Burralong Dr',
  ADDRESS_LOCALITY: 'Wondunna',
  ADDRESS_REGION: 'QLD',
  ADDRESS_POSTCODE: '4655',
  ADDRESS_COUNTRY: 'Australia',
  GOOGLE_MAPS_URL: 'https://maps.google.com/?q=10A+Burralong+Dr,+Wondunna+QLD+4655,+Australia',
  LOCATION: '10A Burralong Dr, Wondunna QLD 4655, Australia',
  FOUNDER: 'Trent Palmer',
  FOUNDER_ROLE: 'Founder & Master Electrician',
  ELECTRICAL_CONTRACTOR_LICENCE: 'Master Electrician #84210',
  NETCC_ACCREDITATION: 'NETCC Approved Solar Retailer',
} as const;
